### ISSUE TITLE
Issue with running graph property prediction.

### ISSUE THREAD

**Issue by ucker** [gravins/Anti-SymmetricDGN#2]
Hi, I noticed that the code for Graph property prediction appears incomplete, such as missing file main_bench.py and self.conv_name in some models. I tried to fix the above issues, but the results I reproduced are much higher than those reported in the paper. Could you provide more details about the experiments of graph property prediction?

**Comment by gravins** [comment]
Hi, thanks for noticing the typo in the run_all.sh file. I fixed the error, now it should work properly. 
All the details, including seeds and data, are already included in the repo. I ran the experiments on 4 Nvidia GPUs A100.
